on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Docker
        # Have to use master to get SKIP_LOGIN fix
        uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true

      - name: Check Docker Version
        run: docker --version

      - name: Check make version
        run: make -v
