on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker
        # Have to use master to get SKIP_LOGIN fix
        uses: actions-hub/docker/cli@master
        env:
          SKIP_LOGIN: true

      - name: Make docker image
        run: make docker

      - name: Generate docs
        run: make dist
